
services:
  api:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

  worker:
    build: .
    env_file:
      - .env
    command: celery -A core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    env_file:
      - .env
    command: celery -A core.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
